#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/fdb
#
# IDENTIFICATION
#    src/backend/storage/fdb/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/fdb
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = fdbaccess.o

include $(top_srcdir)/src/backend/common.mk
